name: stream_control
description: "Remote controller for vMix"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.3.0
  http: ^1.2.2
  flutter_riverpod: ^2.6.1
  equatable: ^2.0.7
  xml: ^6.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
